substitutions:
  plugtag: sonoff_r2_1
  devicename: lab-nodemcu-8266

esphome:
  name: ${devicename}
  board: nodemcuv2
  platform: ESP8266

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: "6fd9b4c5093997a61ab120dca7a6033c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lab-Nodemcu-8266"
    password: "WZO3n27xhFev"

captive_portal:

time:
  - platform: homeassistant
    id: my_time

# Sensors
sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "Lab Desk Temperature"
    humidity:
      name: "Lab Desk Humidity"
    update_interval: 60s
  
  - platform: wifi_signal
    name: "Lab Desk WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    name: "Lab NodeMCU Locator"
    output: led_output
    
output:
  - id: led_output
    platform: gpio
    pin: D1

