###############################################################################
#
# secrets.yaml
#
# ESPHome device secrets
#
###############################################################################
wifi_ssid: ""
wifi_password: ""
ota_password: ""
ap_password: ""
api_password: ""
