###############################################################################
#
# 8266.yaml
#
# ESPHome Generic 8266 Configuration
#
###############################################################################

substitutions:
  plugtag: espressif-8266
  devicename: generic-8266

esphome:
  name: ${devicename}
  board: nodemcuv2
  platform: ESP8266

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
    password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} HotSpot"
    password: !secret ap_password

captive_portal:

time:
  - platform: homeassistant
    id: my_time

sensor:
  - platform: wifi_signal
    name: "${devicename} WiFi Signal"
    update_interval: 60s

